version: '3.8'

services:
  autoscan:
    build: .
    container_name: plex_autoscan
    image: plex_autoscan:latest
    restart: unless-stopped

    # Port mapping
    ports:
      - "3468:3468"

    # Volume mounts
    volumes:
      # Config directory (contains config.json)
      - ./config:/config

      # Database directory (SQLite database)
      - ./database:/app/database

      # Media paths - MUST match Plex container mounts exactly
      - /srv/dev-disk-by-uuid-8f70058d-bad5-42d5-9652-0584223ca05d/Media/Shows:/tv:ro
      - /srv/dev-disk-by-uuid-8f70058d-bad5-42d5-9652-0584223ca05d/Media/Movies:/movies:ro
      - /srv/dev-disk-by-uuid-8f70058d-bad5-42d5-9652-0584223ca05d/Media/MoviesKids:/movieskids:ro
      - /srv/dev-disk-by-uuid-8f70058d-bad5-42d5-9652-0584223ca05d/Media/Anime:/anime:ro
      - /srv/dev-disk-by-uuid-8f70058d-bad5-42d5-9652-0584223ca05d/Media/AnimeMovies:/animemovies:ro

      # Plex database (read-write for WAL mode) - needed for path-to-section mapping
      - /srv/dev-disk-by-uuid-8f70058d-bad5-42d5-9652-0584223ca05d/Config/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases:/plexdb:rw

      # NOTE: With API-based scanning (v2.1+), the following are NO LONGER REQUIRED:
      # - Plex database access (/var/lib/plexmediaserver)
      # - Docker socket (/var/run/docker.sock)
      # - Docker CLI installation
      # The application now uses Plex Media Server API for all scanning operations.

    # Environment variables from .env file
    env_file:
      - .env

    # Additional environment variables (optional)
    environment:
      - TZ=America/New_York  # Set your timezone
      - PUID=1002            # User ID (match Plex/media files owner)
      - PGID=1002            # Group ID (match Plex/media files group)

    # Network configuration
    networks:
      - media_network
      - media_stack_network

    # Health check (just verify server is responding)
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:3468/ > /dev/null || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  media_network:
    driver: bridge
  media_stack_network:
    external: true

# Optional: Define named volumes if using Docker volumes instead of bind mounts
# volumes:
#   plex-config:
#     external: true
